# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc ""
  homepage ""
  version "0.9.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bgetsug/tt/releases/download/v0.9.1/tt_0.9.1_macOS_x86_64.tar.gz"
    sha256 "504ae03ff3e00478d873cbcbfb76532000db1b48fdeea3e747436498e7537e2d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bgetsug/tt/releases/download/v0.9.1/tt_0.9.1_Linux_x86_64.tar.gz"
      sha256 "ea902904e873b3d9880518fa9d32217795e5c813ce48774ac224c5de91924d06"
    end
  end

  def install
    bin.install "tt"
  end
end
